### ISSUE TITLE
Cannot pvp in claims

### ISSUE THREAD

**Issue by xanderc2** [TheFantasyCraft/Forge-Permittor#21]
Hi, i am actually using griefpreventionplus 12.17 and forgerestrictor 1.3.4 i have actually enabled pvp inside claims, and while i try to hit someone it gives a hit, but after the hit i cant hit anymore and the chat broadcast this: you cant build while doing pvp action
also console spams: forge permittor cosficated items for 3ticks.
IF i remove forge restrictor all goes fine, but many items are no longer protected from griefing 
(example ae2 can be dismantled with wrenches inside claims)
so i cant just remove the plugin, any help?

**Comment by thomas15v** [comment]
Normally you can pvp if you are using a weapon. Can you confirm that it works if you are using a diamond sword for example? I realize that using your hand to pvp will proprally be denied. 

Also for the record my plugins does not Confiscate items. Are you sure you aren't using this plugin: https://github.com/KaiKikuchi/ForgeRestrictor

https://github.com/TheFantasyCraft/Forge-Permittor/blob/master/src/main/java/com/fantasycraft/forgepermittor/protection/plugins/GriefPreventionPlusPlugin.java#L45-L46

**Comment by xanderc2** [comment]
Oh yes you are right the error is from forge restrictor, i'm trying both plugins (permittor and restrictor) but are not working like they should, the new ae2 is simply griffable with a wrench D:

**Comment by thomas15v** [comment]
Yeah I am aware of that, and their is sadly enough nothing I can do with that using bukkit. You need to find someone that can patch the mod. I already did something similar for an older version of AE2: https://github.com/thomas15v/DeviantFix . But atm I don't really have time to fix it :disappointed:.
