### ISSUE TITLE
GriefPrevention 9.1 Erro

### ISSUE THREAD

**Issue by Nentify** [TheFantasyCraft/Forge-Permittor#4]
http://pastebin.com/mLTcvU6b

I'm getting this error when interactng with the world on GriefPrevention 9.1.

Could it be because of this change with Claim.allowBuild? https://github.com/ryanhamshire/GriefPrevention/commit/0ec63d6e1c854bbfb02092149e293d2b05861fed

**Comment by thomas15v** [comment]
This happends with Forge-Permittor 0.2-BETA. You could try the 0.3-BETA from here http://ci.thomas15v.net/job/Forge-Permittor/. Meaby that works better :smile:.

**Comment by Nentify** [comment]
I did try the latest version, but it didn't work. A develop of mine forked the project and implemented a fix here: https://github.com/orthoplex64/Forge-Permittor/commit/c23c70c643c625e2cde698153395d961af7a0ddc

The new GriefPrevention has changed the method allowBuild().

**Comment by thomas15v** [comment]
continuing discussion at #5. I am supposing these are caused by the same thing.
