### ISSUE TITLE
[Feacture]Blocking items near claims

### ISSUE THREAD

**Issue by devryb** [TheFantasyCraft/Forge-Permittor#6]
Is it possible for you to add a config option where we can add a list of items to block the right clicking near claims? Example firing a mining laser into the claim from outside of it could be stopped by having a setting like this.

**Comment by thomas15v** [comment]
Hmmm, what your asking is really messy. And will probably not get in to this plugin. Also for the record. I tried this with tekkit-permittor ages ago. And people always find a way to grief with it. 

What version of industrialcraft2 are you using? Maybe if I find some time I write a bytecode patch for it :wink:.

**Comment by devryb** [comment]
I wouldn't put too much effort into that. I can list probably 30-40 items we would need to add to something like this. The mining laser I have no issues just blacklisting from use in the overworld if needed but the 30-40 other items are the challenge.

**Comment by devryb** [comment]
Thought I'd give a list here to show you what I mean.  These are most of the major ones.

Chisel:
 - Cloud in a Bottle (Throwable item that spawn cloud blocks where it lands

Applied Energistics 2:
- Matter Cannon - Gun that destroys blocks and kill animals, similar to mining laser

Thaumcraft:
- All wands - Can cast spells from outside of claim
- Alumentum - Thrown grenade type item, destroys blocks

Minefactory Reloaded
- Needlegun - Can fire into a claim
- Spamr Launcher - Can fire rockets into a claim
- Fishing Rod - Throwing explosive
- Safari Net Launcher - Shoots safari nets to capture mods in claims

Blood Magic:
- Dyanmic Mace - Has a large area of affect on right click destroying blocks in claim from outside it
- Bound Pickaxe - Has a large area of affect on right click destroying blocks in claim from outside it
- Bound Axe - Has a large area of affect on right click destroying blocks in claim from outside it
- Complex Spell Crystal - Can shoot spells into claims, some of them destroy blocks

WR-CBE Addons
- REP - Thrown grenade that damages players

Twilight Forest
- Ore Magnet - Can spawn ores on the surface in a claim
- Crumble Horn - Can destroy cobble/gravel/dirt on the edge of a claim
- Peacock Feather Fan - Can destroy crops in a claim

Botania
- Vine Ball - Spawns vines where thrown
- Shard of Laputa - Moves blocks in an area up into the sky

QuiverBow
- Pretty much all items in this mod bypass pvp

**Comment by thomas15v** [comment]
Holly cow, thats a lot of bytecode patches xD. Akward that that QuiverBow doesn't block. Its kinda sad of thaumcraft :(. I like that mod. I guess I will try something with EntityMoveEvent after my exams :). Like when an entity enters claimed area's from outside, it will be removed.

**Comment by devryb** [comment]
That would probably solve half of the issues listed I would think. The rest we will likely have to make the hard decision on to ban/restrict

**Comment by thomas15v** [comment]
Hmm, As you probably know, bukkit and forge don't work good together. All these block modifying items need to be patches in the forge mod itself. This plugin has been made for mods that give forge/bukkit events and not for dirty fix mod issues. As these dirty fixes always get bypasses. 

For so far I can see I can fix most of it. But these:
- Dyanmic Mace 
- Bound Pickaxe
- Bound Axe
Will require some more work.

This is my idea.
1. Player clicks an item and alerts the entity entering scanner. 
2. We wait 5 ticks and check if their is a new entity around the player.
3. In case their is an entity we scan the loaded chunks around the player for claimed area's.
4. In case of claimed area, we will track the moving entity.
5. In case the entity enters a protected area, it will be killed and the player will be warned.

**Comment by devryb** [comment]
That sounds alright to me, hopefully doesn't require too much cpu time.

**Comment by thomas15v** [comment]
Closing this in favor of patching: https://github.com/densitycraft/Glue. Still being worked at.
